# Generated by Django 6.0.2 on 2026-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('attendance_method', models.CharField(choices=[('manual', 'Manual'), ('barcode_scan', 'Barcode Scan'), ('qr_scan', 'QR Scan'), ('auto_online', 'Auto Online')], default='manual', max_length=15)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_info', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('scan_attempt', 'Scan Attempt')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_url', models.URLField(blank=True, help_text='Zoom or meeting URL')),
                ('meeting_id', models.CharField(blank=True, max_length=50)),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('recording_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(help_text='Encrypted student ID', max_length=255, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='student_ids/barcodes/')),
                ('qr_code_image', models.ImageField(blank=True, upload_to='student_ids/qrcodes/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Student Barcode',
                'verbose_name_plural': 'Student Barcodes',
            },
        ),
    ]
