# Generated by Django 6.0.2 on 2026-02-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='live_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.liveclass'),
        ),
        migrations.AddField(
            model_name='studentbarcode',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('live_class', 'student')},
        ),
    ]
